apiVersion: v1
kind: Service
metadata:
  name: app-loadbalancer-service
  labels:
    app: firefly-iii
spec:
  type: LoadBalancer
  selector:
    app: firefly-iii
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
