apiVersion: v1
kind: Service
metadata:
  name: csv-loadbalancer-service
  labels:
    app: firefly-iii-csv
spec:
  type: LoadBalancer
  selector:
    app: firefly-iii-csv
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
